apiVersion: apps/v1
kind: Deployment
metadata:
  name: screen-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: screen-web
  template:
    metadata:
      labels:
        app: screen-web
    spec:
      containers:
        - name: screen-web
          image: tal5041996/screen_web:7
          imagePullPolicy: Always
          env:
            - name: MINIO_ENDPOINT
              value: 'minio:9000'
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secretkey
            - name: MINIO_BUCKET_NAME
              value: "screenshots"
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb.database.svc.cluster.local:27017/website_screenshots?authSource=admin"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: screen-web
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: screen-web